#!/bin/bash

CMD=$1
shift 1
ARGS=$@

source .env

dev() {
  local WEBPACK=node_modules/webpack/bin/webpack.js
  local WEBPACK_DEV_SERVER=node_modules/webpack-dev-server/bin/webpack-dev-server.js
  trap 'kill $(jobs -p)' EXIT
    $WEBPACK -w &
    $WEBPACK_DEV_SERVER --hot --inline --host 0.0.0.0 --port 8008 --content-base public/ &
  wait
}

build() {
  local WEBPACK=node_modules/webpack/bin/webpack.js
  WEBPACK -p
}

deploy() {
  docker pull xueshanf/awscli
  docker run --rm \
    -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
    -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
    -e AWS_DEFAULT_REGION=us-east-1 \
    -v $PWD:/app xueshanf/awscli\
      aws s3 cp \
        --recursive \
        --acl public-read \
        --cache-control max-age=600 \
        ./public $DEPLOY_S3_PATH

}

$CMD $ARGS
